package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"
	"shelf/db/models"
	"shelf/graph/model"
	"time"

	"github.com/google/uuid"
)

// CreateBookmark is the resolver for the createBookmark field.
func (r *mutationResolver) CreateBookmark(ctx context.Context, input model.CreateBookmarkInput) (*models.Bookmark, error) {
	profileID, ok := ctx.Value("userID").(uuid.UUID)
	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}

	bookmark := &models.Bookmark{
		ProfileID: profileID,
		URL:       input.URL,
		Title:     input.Title,
		Notes:     input.Notes,
		Status:    models.EnrichmentPending,
		CursorKey: fmt.Sprintf("%s::%s", time.Now().UTC().Format(time.RFC3339), uuid.New().String()),
	}

	if err := r.DB.Create(bookmark).Error; err != nil {
		return nil, err
	}

	// attach tags if provided
	if len(input.TagNames) > 0 {
		var tags []models.Tag
		for _, name := range input.TagNames {
			var tag models.Tag
			// upsert — find existing tag or create new one for this profile
			err := r.DB.Where(models.Tag{ProfileID: profileID, Name: name}).
				FirstOrCreate(&tag).Error
			if err != nil {
				return nil, fmt.Errorf("failed to create tag %s: %w", name, err)
			}
			tags = append(tags, tag)
		}
		if err := r.DB.Model(bookmark).Association("Tags").Replace(tags); err != nil {
			return nil, fmt.Errorf("failed to attach tags: %w", err)
		}
	}

	// reload bookmark with tags
	if err := r.DB.Preload("Tags").First(bookmark, bookmark.ID).Error; err != nil {
		return nil, err
	}

	return bookmark, nil
}

// UpdateBookmark is the resolver for the updateBookmark field.
func (r *mutationResolver) UpdateBookmark(ctx context.Context, id uuid.UUID, input model.UpdateBookmarkInput) (*models.Bookmark, error) {
	profileID, ok := ctx.Value("userID").(uuid.UUID)
	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}

	var bookmark models.Bookmark
	if err := r.DB.Where("id = ? AND profile_id = ?", id, profileID).First(&bookmark).Error; err != nil {
		return nil, fmt.Errorf("bookmark not found")
	}

	if input.Title != nil {
		bookmark.Title = input.Title
	}
	if input.Notes != nil {
		bookmark.Notes = input.Notes
	}
	if input.Status != nil {
		bookmark.Status = models.EnrichmentStatus(*input.Status)
	}

	if err := r.DB.Save(&bookmark).Error; err != nil {
		return nil, err
	}

	if len(input.TagNames) > 0 {
		var tags []models.Tag
		for _, name := range input.TagNames {
			var tag models.Tag
			err := r.DB.Where(models.Tag{ProfileID: profileID, Name: name}).
				FirstOrCreate(&tag).Error
			if err != nil {
				return nil, fmt.Errorf("failed to upsert tag %s: %w", name, err)
			}
			tags = append(tags, tag)
		}
		if err := r.DB.Model(&bookmark).Association("Tags").Replace(tags); err != nil {
			return nil, fmt.Errorf("failed to update tags: %w", err)
		}
	}

	if err := r.DB.Preload("Tags").First(&bookmark, bookmark.ID).Error; err != nil {
		return nil, err
	}

	return &bookmark, nil
}

// DeleteBookmark is the resolver for the deleteBookmark field.
func (r *mutationResolver) DeleteBookmark(ctx context.Context, id uuid.UUID) (bool, error) {
	profileID, ok := ctx.Value("userID").(uuid.UUID)
	if !ok {
		return false, fmt.Errorf("unauthorized")
	}

	result := r.DB.Where("id = ? AND profile_id = ?", id, profileID).Delete(&models.Bookmark{})
	if result.Error != nil {
		return false, result.Error
	}
	if result.RowsAffected == 0 {
		return false, fmt.Errorf("bookmark not found")
	}

	return true, nil
}

// CreateTag is the resolver for the createTag field.
func (r *mutationResolver) CreateTag(ctx context.Context, name string) (*models.Tag, error) {
	profileID, ok := ctx.Value("userID").(uuid.UUID)
	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}

	var tag models.Tag
	err := r.DB.Where(models.Tag{ProfileID: profileID, Name: name}).
		FirstOrCreate(&tag).Error
	if err != nil {
		return nil, err
	}

	return &tag, nil
}

// DeleteTag is the resolver for the deleteTag field.
func (r *mutationResolver) DeleteTag(ctx context.Context, id uuid.UUID) (bool, error) {
	profileID, ok := ctx.Value("userID").(uuid.UUID)
	if !ok {
		return false, fmt.Errorf("unauthorized")
	}

	result := r.DB.Where("id = ? AND profile_id = ?", id, profileID).Delete(&models.Tag{})
	if result.Error != nil {
		return false, result.Error
	}
	if result.RowsAffected == 0 {
		return false, fmt.Errorf("tag not found")
	}

	return true, nil
}

// Bookmarks is the resolver for the bookmarks field.
func (r *queryResolver) Bookmarks(ctx context.Context, tag *string, search *string, limit *int, after *string) (*model.BookmarkConnection, error) {
	profileID, ok := ctx.Value("userID").(uuid.UUID)
	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}

	pageSize := 10
	if limit != nil && *limit > 0 {
		pageSize = *limit
	}

	// fix: prefix with table name
	query := r.DB.Where("bookmarks.profile_id = ?", profileID).Preload("Tags")

	if after != nil && *after != "" {
		query = query.Where("bookmarks.cursor_key < ?", *after)
	}

	// fix: prefix t.profile_id
	if tag != nil && *tag != "" {
		query = query.Joins("JOIN bookmark_tags bt ON bt.bookmark_id = bookmarks.id").
			Joins("JOIN tags t ON t.id = bt.tag_id").
			Where("t.name = ? AND t.profile_id = ?", *tag, profileID)
	}

	// fix: prefix bookmarks.title and bookmarks.url
	if search != nil && *search != "" {
		query = query.Where("bookmarks.title ILIKE ? OR bookmarks.url ILIKE ?",
			"%"+*search+"%", "%"+*search+"%")
	}

	var bookmarks []models.Bookmark
	if err := query.Order("bookmarks.cursor_key DESC").Limit(pageSize + 1).Find(&bookmarks).Error; err != nil {
		return nil, err
	}

	hasNextPage := len(bookmarks) > pageSize
	if hasNextPage {
		bookmarks = bookmarks[:pageSize]
	}

	edges := make([]*model.BookmarkEdge, len(bookmarks))
	for i, b := range bookmarks {
		b := b
		edges[i] = &model.BookmarkEdge{
			Cursor: b.CursorKey,
			Node:   &b,
		}
	}

	var endCursor *string
	if len(bookmarks) > 0 {
		c := bookmarks[len(bookmarks)-1].CursorKey
		endCursor = &c
	}

	return &model.BookmarkConnection{
		Edges: edges,
		PageInfo: &model.PageInfo{
			HasNextPage: hasNextPage,
			EndCursor:   endCursor,
		},
	}, nil
}

// Bookmark is the resolver for the bookmark field.
func (r *queryResolver) Bookmark(ctx context.Context, id uuid.UUID) (*models.Bookmark, error) {
	profileID, ok := ctx.Value("userID").(uuid.UUID)
	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}

	var bookmark models.Bookmark
	if err := r.DB.Preload("Tags").
		Where("id = ? AND profile_id = ?", id, profileID).
		First(&bookmark).Error; err != nil {
		return nil, fmt.Errorf("bookmark not found")
	}

	return &bookmark, nil
}

// Tags is the resolver for the tags field.
func (r *queryResolver) Tags(ctx context.Context) ([]*models.Tag, error) {
	profileID, ok := ctx.Value("userID").(uuid.UUID)
	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}

	var tags []*models.Tag
	if err := r.DB.Where("profile_id = ?", profileID).Find(&tags).Error; err != nil {
		return nil, err
	}

	return tags, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
