// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"shelf/db/models"
	"time"

	"github.com/google/uuid"
)

type BookmarkConnection struct {
	Edges    []*BookmarkEdge `json:"edges"`
	PageInfo *PageInfo       `json:"pageInfo"`
}

type BookmarkEdge struct {
	Cursor string           `json:"cursor"`
	Node   *models.Bookmark `json:"node"`
}

type CreateBookmarkInput struct {
	URL      string   `json:"url"`
	Title    *string  `json:"title,omitempty"`
	Notes    *string  `json:"notes,omitempty"`
	TagNames []string `json:"tagNames,omitempty"`
}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage bool    `json:"hasNextPage"`
	EndCursor   *string `json:"endCursor,omitempty"`
}

type Profile struct {
	ID        uuid.UUID          `json:"id"`
	Email     string             `json:"email"`
	Username  string             `json:"username"`
	FirstName string             `json:"firstName"`
	LastName  *string            `json:"lastName,omitempty"`
	Avatar    string             `json:"avatar"`
	Bookmarks []*models.Bookmark `json:"bookmarks"`
	Tags      []*models.Tag      `json:"tags"`
	CreatedAt time.Time          `json:"createdAt"`
}

type Query struct {
}

type UpdateBookmarkInput struct {
	Title    *string                  `json:"title,omitempty"`
	Notes    *string                  `json:"notes,omitempty"`
	TagNames []string                 `json:"tagNames,omitempty"`
	Status   *models.EnrichmentStatus `json:"status,omitempty"`
}
